name: conference_darwin
description: >
  A library for building conference schedules using a genetic algorithm.
version: 0.0.1
#homepage: https://www.example.com
#author: filiph <email@example.com>

environment:
  sdk: '>=1.20.1 <2.16.3'
dependencies: 
  darwin: ^0.5.1
  yaml: ^3.1.0
dev_dependencies:
  test: ^1.21.1
